{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "security-log-search.fullname" . }}
  labels:
    {{- include "security-log-search.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "security-log-search.selectorLabels" . | nindent 6 }}
{{- end }}
