{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "security-log-search.serviceAccountName" . }}
  labels:
    {{- include "security-log-search.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "security-log-search.fullname" . }}
  labels:
    {{- include "security-log-search.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.serviceAccount.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "security-log-search.fullname" . }}
  labels:
    {{- include "security-log-search.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "security-log-search.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "security-log-search.fullname" . }}
{{- end }}
{{- end }}
