apiVersion: v1
kind: Service
metadata:
  name: security-log-search
  namespace: security-log-search
  labels:
    app.kubernetes.io/name: security-log-search
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: security-log-search
  ports:
    - name: http
      port: 80
      targetPort: http
