replicaCount: 2

resources:
  requests:
    cpu: 300m
    memory: 768Mi
  limits:
    cpu: "1500m"
    memory: 1.5Gi

autoscaling:
  minReplicas: 2
  maxReplicas: 6

podDisruptionBudget:
  minAvailable: 1
