apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-log-search.fullname" . }}
  labels:
    {{- include "security-log-search.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "security-log-search.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
